<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy扩展库使用" data-toc-modified-id="Numpy扩展库使用-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Numpy扩展库使用<br></a></span><ul class="toc-item"><li><span><a href="#数组的创建" data-toc-modified-id="数组的创建-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>数组的创建<br></a></span><ul class="toc-item"><li><span><a href="#numpy.array()-——-由列表、元组创建数组" data-toc-modified-id="numpy.array()-——-由列表、元组创建数组-11.1.1"><span class="toc-item-num">11.1.1&nbsp;&nbsp;</span>numpy.array() —— 由列表、元组创建数组</a></span></li><li><span><a href="#由函数创建特殊数组" data-toc-modified-id="由函数创建特殊数组-11.1.2"><span class="toc-item-num">11.1.2&nbsp;&nbsp;</span>由函数创建特殊数组<br></a></span></li></ul></li><li><span><a href="#数组的属性" data-toc-modified-id="数组的属性-11.2"><span class="toc-item-num">11.2&nbsp;&nbsp;</span>数组的属性<br></a></span></li><li><span><a href="#数组元素的访问" data-toc-modified-id="数组元素的访问-11.3"><span class="toc-item-num">11.3&nbsp;&nbsp;</span>数组元素的访问<br></a></span></li><li><span><a href="#数组内容操作" data-toc-modified-id="数组内容操作-11.4"><span class="toc-item-num">11.4&nbsp;&nbsp;</span>数组内容操作<br></a></span></li><li><span><a href="#数组的view()-与copy()" data-toc-modified-id="数组的view()-与copy()-11.5"><span class="toc-item-num">11.5&nbsp;&nbsp;</span>数组的view() 与copy()</a></span></li><li><span><a href="#数组形状操作" data-toc-modified-id="数组形状操作-11.6"><span class="toc-item-num">11.6&nbsp;&nbsp;</span>数组形状操作<br></a></span></li><li><span><a href="#数组与数值的运算" data-toc-modified-id="数组与数值的运算-11.7"><span class="toc-item-num">11.7&nbsp;&nbsp;</span>数组与数值的运算<br></a></span></li><li><span><a href="#数组与数组的运算" data-toc-modified-id="数组与数组的运算-11.8"><span class="toc-item-num">11.8&nbsp;&nbsp;</span>数组与数组的运算<br></a></span></li><li><span><a href="#广播" data-toc-modified-id="广播-11.9"><span class="toc-item-num">11.9&nbsp;&nbsp;</span>广播<br></a></span></li><li><span><a href="#线性代数" data-toc-modified-id="线性代数-11.10"><span class="toc-item-num">11.10&nbsp;&nbsp;</span>线性代数<br></a></span></li><li><span><a href="#数学函数" data-toc-modified-id="数学函数-11.11"><span class="toc-item-num">11.11&nbsp;&nbsp;</span>数学函数</a></span></li><li><span><a href="#排序、搜索、计数" data-toc-modified-id="排序、搜索、计数-11.12"><span class="toc-item-num">11.12&nbsp;&nbsp;</span>排序、搜索、计数</a></span></li><li><span><a href="#统计函数" data-toc-modified-id="统计函数-11.13"><span class="toc-item-num">11.13&nbsp;&nbsp;</span>统计函数</a></span></li></ul></li></ul></div>

# Numpy扩展库使用<br>
<font face='kaiti' size=5 style='line-height:1.5'>
    
&emsp;&emsp;用于数据分析、科学计算与可视化的Python扩展模块有很多，如：numpy、scipy、pandas、matplotlib、SymPy、Traits、TraitsUI、Chaco、TVTK、Mayavi、VPython、OpenCV。    
&emsp;&emsp;Numpy是Python的科学计算包，主要用于对多维数组执行计算。NumPy这个词来源于两个单词-- Numerical和Python。使用前需先导入，习惯上常写做：`import numpy as np`. <p>
&emsp;&emsp;Numpy中提供的最重要的数据结构是一个称为NumPy数组的强大对象ndarrays，Numpy的运算都基于该数组展开。Numpy还提供一个Matrix类，提供类似MATLAB中矩阵的使用方法。<br>
https://www.numpy.org/devdocs/user/quickstart.html <br>
https://www.numpy.org/devdocs/reference/routines.html <br>
https://www.numpy.org.cn/  <br>
http://www.runoob.com/numpy/numpy-statistical-functions.html

## 数组的创建<br>
<font face='kaiti' size=5 style='line-height:1.5'>
    
&emsp;&emsp;Numpy中创建数组有多种方法，下面列出其中常用的两种：
1. 由列表、元组通过函数numpy.array()创建；
2. 由其他函数创建特殊的数组，如arange()，linspace(), ones(), zeros(), random()等。

&emsp;&emsp;对Numpy创建的数组，在命令窗口中用print输出和直接输出的表现形式不同。

### numpy.array() —— 由列表、元组创建数组
<font face='kaiti' size=5 style='line-height:1.5'>

In [11]:
# 创建一维数组
import numpy as np
x11 = np.array([[2,3,1,0],[2,3,4,1]])  # 用列表创建数组
print(x11) 
print(x11.ndim)
type(x11)

[[2 3 1 0]
 [2 3 4 1]]
2


numpy.ndarray

In [63]:
# 创建一维数组
import numpy as np
x11 = np.array((2,3,1,0))   # 用元组创建数组
x11  # 直接输出

array([2, 3, 1, 0])

In [19]:
# 创建二维数组，元素可以是复数
import numpy as np  # 若前面已经导入过numpy，则后面可以直接使用，不用再导入
x12 = np.array([[ 1.+0.j, 2], [0, 0.+0.j], [ 1.+1.j, 3.+0.j]])
print(x12)
x12.ndim

[[1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j]]


2

In [20]:
# 下面的是二维数组哦！相当于单行的矩阵，注意区别
x13 = np.array([[2,3,1,0]])
print(x13)
x13.ndim

[[2 3 1 0]]


2

In [27]:
# 下面创建的也是二维数组，相当于单列的矩阵
x14 = np.array([[1],[2],[3],[4]])
print(x14)
x14.ndim

[[1]
 [2]
 [3]
 [4]]


2

### 由函数创建特殊数组<br>
<font face='kaiti' size=5 style='line-height:1.5'>

1. arange(), linspace() ：  创建规则递增或递减的数组
2. ones(), zeros()： 创建全1数组、全0数组
3. eye(), diag()： 创建单位阵、对角阵
4. full(), empty()： 用给定值填充，或仅占位
5. random： 随机数模块，可创建随机数组

<font face='kaiti' size=5, style='line-height:1.5'>

1. arange(), linspace() ：  创建等差数列； <br>
  另有logspace()： 创建等比数列，自己查阅资料

In [29]:
# numpy.arange() 创建等差数列
x21 = np.arange(5)   # 注意: 是arange，不是range。range是Python的内置函数
print(x21)
x21 = np.arange(1,10,2)
print(x21)
x21 = np.arange(10,1,-2)
x21

[0 1 2 3 4]
[1 3 5 7 9]


array([10,  8,  6,  4,  2])

In [35]:
# numpy.linspace() 创建等差数列
x22 = np.linspace(0, 5, 11)  # 创建 0为起点，5为终点，等间隔的11个点，包含5
print(x22)
x22 = np.linspace(0, 5, 10, endpoint=False)   # 不包含5
x22

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

<font face='kaiti' size=5>

2. ones(), zeros() ： 创建全1数组、全0数组

In [48]:
# numpy.ones() 创建全1数组
x23 = np.ones(5)
print(x23)
x23 = np.ones([4,5])  # 创建全1矩阵，行数和列数需放在 1 个列表或元组中，当做一个输入参数
x23

[1. 1. 1. 1. 1.]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
# numpy.zeros() 创建全0数组
x24 = np.zeros(3)
print(x24)
np.zeros((3,3))    

[0. 0. 0.]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<font face='kaiti' size=5>

3. eye(), diag(): 单位阵，对角阵

In [228]:
x31 = np.eye(3)
print(x31)
np.eye(3,5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [235]:
# diag()可用于由一维数组创建对角阵，也可求矩阵的对角元素返回一维数组
x32 = np.diag([1,2,3,4])
print(x32)
x33 = np.diag(np.arange(1,5), 1)
print('\n', x33)
x = np.arange(16).reshape(4,4)
print('\n', x)
x34 = np.diag(x)
print('\n', x34)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

 [[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [ 0  5 10 15]


<font face='kaiti' size=5 style='line-height:1.5'>

4. full(), empty()： 用给定值填充，或仅占位

In [51]:
np.full((2,5),3)   # 创建2行5列，元素取值均为3的数组

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [62]:
np.empty([2,5])   # 创建一个3行5列的数组，元素随机，用于初始化

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

<font face='kaiti' size=5 style='line-height:1.5'>
    
5. random： numpy中有一个random模块，用于随机数数组的生成。提供了大量的函数，可生成服从各种分布的数组，也可以生成随机整数列。

In [36]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [37]:
np.random.randint(10, size=5)      # 随机数组，5个[0, 10)上的随机整数

array([1, 8, 9, 4, 3])

In [237]:
np.random.randint(0, 50, (3,5))    # 3行5列的随机数组，15个[0,50)上的随机整数

array([[20,  3, 11,  3, 39],
       [ 6, 18, 35, 34,  9],
       [10, 29, 10, 38, 12]])

In [239]:
np.random.rand(3, 4)               # 3行4列的随机数组，数据服从[0, 1]上均匀分布

array([[0.17030157, 0.76505099, 0.01284823, 0.21470602],
       [0.51762894, 0.31675429, 0.11942628, 0.67533121],
       [0.83975076, 0.16238528, 0.46977362, 0.22050391]])

In [240]:
np.random.standard_normal(5)     # 从标准正态分布中随机采样

array([ 0.16954168, -1.7842579 , -0.70560158,  0.40238515, -1.31559363])

In [307]:
np.random.standard_normal(size=(3, 4))

array([[ 0.6621641 ,  1.25748935,  1.37989172,  0.47578539],
       [ 0.52361516, -1.380612  , -1.63378183, -0.83424119],
       [ 0.29833088, -0.71606921, -0.18654715,  0.27011554]])

## 数组的属性<br>
<font face='kaiti' size=5 style='line-height:1.5'>

&emsp;&emsp;Numpy中多维数组的维度又称为“轴”，如数组`np.array([1,2,3])`只有1个轴(axis = 0)，长度为3；数组`np.array([[1,2,3],[2,3,4]])`有2个轴，第1个轴(axis = 0)长度为2，第2个轴(axis = 1)长度为3. <br>
&emsp;&emsp;Numpy中提供了一些函数或方法用于获取数组的属性。
1. ndim: 获取数组的维数
2. size: 获取数组的元素个数
3. shape: 获取数组的大小，也可以用于改变数组的大小

&emsp;&emsp;注意与MATLAB中对应功能函数的区别！上述函数可当做numpy的函数使用，也可当做数组的方法使用。此外，numpy的数组还有dtype, itemsize等属性，分别描述数组的元素类型，每个元素的字节数。

In [195]:
x = np.random.random((3,5))
print(x)
print('数组x的维数为：', x.ndim)
print('数组x的维数为：', np.ndim(x))
print('数组x的元素个数为：', x.size)
print('数组x的元素个数为：', np.size(x))
print('数组x的行数为：', np.size(x, 0))   # 数组第 1维的长度
print('数组x的列数为：', np.size(x, 1))   # 数组第 2维的长度
print('数组x的大小为：', x.shape)
print('数组x的大小为：', np.shape(x))
print('数组x的元素类型：', x.dtype)
print('数组x的元素的字节数：', x.itemsize)

[[0.60547661 0.43174265 0.77423078 0.53438459 0.67355711]
 [0.68084646 0.55409421 0.49261062 0.28850835 0.80807296]
 [0.23446144 0.48693496 0.67933148 0.83399259 0.97887995]]
数组x的维数为： 2
数组x的维数为： 2
数组x的元素个数为： 15
数组x的元素个数为： 15
数组x的行数为： 3
数组x的列数为： 5
数组x的大小为： (3, 5)
数组x的大小为： (3, 5)
数组x的元素类型： float64
数组x的元素的字节数： 8


In [200]:
x1 = np.arange(5)
print('x1的维数：', x1.ndim)
print('x1的大小：', x1.shape)
x2 = 5
print('x2的维数：', np.ndim(x2))  # 单独一个数的维数为0， 不能用 x2.ndim
print('x2的大小：', np.shape(x2)) 

x1的维数： 1
x1的大小： (5,)
x2的维数： 0
x2的大小： ()


In [438]:
# shape属性改变数组的大小，这是原地操作
x = np.arange(12)
x.shape = 3, 4
print(x)
print(id(x))
x.shape = 2, -1  # -1 表示该维自动计算
print(x)
print(id(x))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
96525408
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
96525408


## 数组元素的访问<br>
<font face='kaiti' size=5 style='line-height:1.5'>

&emsp;&emsp;在数组变量名后使用方括号表示数组的元素。方括号内可以用索引，也可以用切片，用法与列表元素的访问一致，同样支持双向索引。对n维数组a, `a[]...[]`后面的方括号分别对应axis=0, axis=1, ..., axis =n-1 上的索引号。如果方括号的个数少于数组的维数，则同时访问后面其余轴的多个元素。

In [85]:
# 一维数组的访问
x = np.arange(5)
print(x)
print('x[2] =', x[2])
print('x[-1] =', x[-1])
print('x[1:3] =', x[1:3])
print('x[::-1] =', x[::-1])

[0 1 2 3 4]
x[2] = 2
x[-1] = 4
x[1:3] = [1 2]
x[::-1] = [4 3 2 1 0]


In [101]:
## 二维数组的访问
x = np.array([[0, 1, 2, 3, 4], 
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])
print('x[1,2] =', x[1,2])
print('x[1,:] =', x[1,:])
print('x[:,2] =', x[:,2])
print('x[2] =', x[2])  # 索引号为2的行，访问多个元素
x[-1] = [1,2,3,4,5]    # 修改最后一行
x

x[1,2] = 7
x[1,:] = [5 6 7 8 9]
x[:,2] = [ 2  7 12]
x[2] = [10 11 12 13 14]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;数组也可以作为可迭代对象，参与迭代。对多维数组迭代是相对于第一个轴（对矩阵，相当于行）完成的。

In [97]:
x = np.array([[0, 1, 2, 3, 4], 
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])
for row in x:
    print(row)


[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


## 数组内容操作<br>
<font face='kaiti' size=5 style='line-height:1.5'>
    
&emsp;&emsp;Numpy数组可以进行添加元素、删除元素、修改元素等内容操作

In [478]:
x = np.arange(5)
print(x)
print(np.append(x, 7))  # 增加元素，返回新数组，append()不能作为数组的方法
x[0] = -3   # 原地操作，修改元素，索引号不能超出范围
print(x)
print(np.insert(x, 1, 8))  # 索引号为1的位置插入元素，返回新数组，insert()不能作为数组的方法
print(x.repeat(2))  # x 重复，返回新数组

[0 1 2 3 4]
[0 1 2 3 4 7]
[-3  1  2  3  4]
[-3  8  1  2  3  4]
[-3 -3  1  1  2  2  3  3  4  4]


## 数组的view() 与copy()
<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;像列表一样，numpy创建的数组也是可变数据类型。因为Python中基于值的内存管理模式，当指向数组的变量a赋值给变量b时，两个变量指向的内存地址一致，若对其中一个变量指向的数组做原地操作，则另一个变量也受同样的影响。

In [26]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a
a.shape = 2,6
print('a =\n', a)
print('b =\n', b)  # a,b的形状一起改变
b[0,0] = 100
print('a =\n', a)  # a,b的数据一起改变

a =
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
b =
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a =
 [[100   2   3   4   5   6]
 [  7   8   9  10  11  12]]


<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;Numpy提供一种复制数组的view()方法，创建的新数组与原数组的地址不同，但数据共享。相当于Python的浅复制。    

In [446]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a.view()
print('a =\n', a)
print('b =\n', b)   # a的形状改变不影响 b的形状
b[0,0] = 100
print(a)   # a,b数据共享。b的数据改变，则 a的同样改变

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4   5   6]
 [  7   8   9  10  11  12]]


<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;若希望复制后的2个变量指向的数组在此后各自的操作中互不影响，则需用到数组的copy()方法. copy()方法生成数组及其数据的完全拷贝，相当于Python中的深复制。 

In [447]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a.copy()
a.shape = 2,6
print('a =\n', a)
print('b =\n', b)  # a的形状改变不影响 b的形状
b[0,0] = 100
print(a)  # a,b的数据不共享，改变b的数据不影响 a的数据

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## 数组形状操作<br>
<font face='kaiti' size=5 style='line-height:1.5'>

&emsp;&emsp;对数组的shape属性赋值能改变数组的形状。除此之外，还有一些函数也可用于数组的形状操作。
- 更改数组的形状：  reshape(),  resize(),  ravel(), flatten(), transpose(), T()
- 数组堆叠： hstack(), vstack()

<font face='kaiti' size=5 style='line-height:1.5'>

1. 更改数组的形状： reshape(),  resize(),  ravel(), flatten(), transpose(), T()

<font face='kaiti' size=5 style='line-height:1.5'>
    
&emsp;`reshape(a, newshape, order='C')`用于改变数组a的形状，默认按行优先`order='C'`的方式重排，也可按列优先`order='F'`的方式重排，要求重排后的数组元素个数相同。reshape()返回一个新数组，并不改变原数组本身，且新数组与原数组的数据共享，即对其中一个做原地操作，另一个同样改变。reshape()即可当做numpy的函数使用，也可当做数组的方法使用。

In [480]:
# reshape() 当做 numpy的函数使用
x = np.arange(6)
print('x =', x)
x1 = np.reshape(x, (2,3), 'c')  # 按行重排
print('x1 =\n', x1)
x2 = np.reshape(x, (2,3), 'f')  # 按列重排
print('x2 =\n', x2)
x3 = np.reshape(x, (3,-1))  # 默认按行重排，若维度指定为-1，则自动计算该维度大小
print('x3 =\n', x3)
print('x =', x)  # 不改变原数组本身
x4 = np.reshape(x3, -1)  # 返回对 x3的按行平铺的行向量
print('x4 =\n', x4)
x5 = np.reshape(x3, -1, 'f')  # 返回对 x3的按列平铺的行向量
print('x5 =\n', x5)
x6 = np.reshape(x3, (-1,1), 'f')  # 返回对 x3的按列平铺的列向量
print('x6 =\n', x6)

x = [0 1 2 3 4 5]
x1 =
 [[0 1 2]
 [3 4 5]]
x2 =
 [[0 2 4]
 [1 3 5]]
x3 =
 [[0 1]
 [2 3]
 [4 5]]
x = [0 1 2 3 4 5]
x4 =
 [0 1 2 3 4 5]
x5 =
 [0 2 4 1 3 5]
x6 =
 [[0]
 [2]
 [4]
 [1]
 [3]
 [5]]


In [306]:
x6 = np.arange(24).reshape(3,2,4)  # 返回一个三维数组
print('x6 =\n', x6)

x6 =
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [168]:
# reshape() 当做数组的方法使用
x = np.arange(12)
print('x =', x)
x1 = x.reshape(2, 6, order='f')   # 按行重排为2行6列的数组，返回重排后的数组
print('x1 =\n', x1) 
x2 = x.reshape(2, 6, order='f')   # 按列重排为2行6列的数组，返回重排后的数组
print('x2 =\n', x2)
x3 = x.reshape(3,-1)  # 维度指定为-1，则自动计算该维度
print('x3 =\n', x3)
print('x =', x)  # 使用reshape()重排后，不改变原数组的大小
x3.reshape(-1, order='f')  # 返回 对x按列平铺的数组

x = [ 0  1  2  3  4  5  6  7  8  9 10 11]
x1 =
 [[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
x2 =
 [[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
x3 =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
x = [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [423]:
x = np.arange(12)
x1 = np.reshape(x, (2,6), 'c')
x[3] = 7  # 改变 x 的元素的值，由x用reshape()变形得到的x1同样改变
print(x1)

[[ 0  1  2  7  4  5]
 [ 6  7  8  9 10 11]]


<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;`resize(a, new_shape)`也用于改变数组a的形状，但只能按行重排，也不允许使用'-1'作为维度。当做numpy的函数使用时，返回一个新数组，当做数组的方法使用时，改变原数组的形状。另外，与reshape()不同的是，resize()函数可允许新矩阵的元素数多于原矩阵元素数，若resize()作为numpy的函数使用，则用原数组的元素填充增加的元素。若作为数组的方法使用，则用0填充增加的元素。另外，resize()作为numpy的函数使用时，返回的新数组与原数组的数据不共享。

In [426]:
# resize() 用于改变数组的形状
x = np.arange(12)
print(x)
x2 = np.resize(x, (2, 6))  # 返回重排后的数组
print('x2 =\n', x2)
x3 = x.resize(2, 6)  
print('x3 =', x3)   # 返回为空
print('x =\n', x)   # resize()当做数组的方法使用，改变原数组的大小
x4 = np.resize(x, (3, 8))
print('x4 =\n', x4)  # 当新形状的元素数量大于原数量时，使用原数组的元素填充
x.resize((3,8))
x

[ 0  1  2  3  4  5  6  7  8  9 10 11]
x2 =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
x3 = None
x =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
x4 =
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11  0  1  2  3]
 [ 4  5  6  7  8  9 10 11]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [27]:
# np.resize()返回的新数组的元素不是原数组元素的引用
x = np.arange(12)
x2 = np.resize(x, (2, 6))  # 返回重排后的数组
x[3] = 100
print(x)
print(x2)

[  0   1   2 100   4   5   6   7   8   9  10  11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;`ravel(a, order='C')`与`a.flatten(order='C')`都可以用于数组a的按行平铺或按列平铺，返回一个新数组，原数组不改变。但ravel()既可作为numpy的函数，又可作为数组的方法使用，而flatten()只能作为数组的方法使用。另外，ravel()返回的数组的元素是原数组的元素的引用，而flatten()返回的数组的元素不是原数组的元素的引用。

In [419]:
x = np.arange(12).reshape(3,4)
y = x.ravel()
x[0][0] = 5
y

array([ 5,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [374]:
# flatten()的用法
x = np.arange(12).reshape(3,4)
print(x)
print('按行重排：', x.flatten('c'))  # 按行重排
print('按列重排：', x.flatten('f'))  # 按列重排
print('默认按行重排：', x.flatten())   # 默认按行重排
x  # 不改变 x本身

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
按行重排： [ 0  1  2  3  4  5  6  7  8  9 10 11]
按列重排： [ 0  4  8  1  5  9  2  6 10  3  7 11]
默认按行重排： [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [420]:
# ravel()的含义与flatten()相同，但可作为方法，也可作为函数
x = np.arange(12).reshape(3,4)
print('x =\n', x)
print('x.ravel() =\n', x.ravel())  # ravel()作为数组x的方法
print('np.ravel(x) =\n', np.ravel(x))  # ravel()作为numpy的函数
print('x.ravel("f") =\n', x.ravel('f'))  # 按列平铺
print('np.ravel(x, "f") =\n', np.ravel(x,'f'))  # 按列平铺

x =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
x.ravel() =
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
np.ravel(x) =
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
x.ravel("f") =
 [ 0  4  8  1  5  9  2  6 10  3  7 11]
np.ravel(x, "f") =
 [ 0  4  8  1  5  9  2  6 10  3  7 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [427]:
x = np.arange(12).reshape(3,4)
x1 = x.ravel()  # ravel()返回的数组的元素是原数组元素的引用
x2 = x.flatten()  # flatten()返回的数组的元素不是原数组元素的引用
x[0][2] = 7
print('x = \n', x)
print('x1 =\n', x1)
print('x2 =\n', x2)

x =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
x = 
 [[ 0  1  7  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
x1 =
 [ 0  1  7  3  4  5  6  7  8  9 10 11]
x2 =
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;`transpose(a, axes=None)`用于数组a的转置。返回一个新数组，但不改变a本身，且新数组与原数组的数据共享。对于二维数组a，`numpy.transpose(a)`和`a.transpose()`均表示数组 a 的转置。对于一维数组a，返回a.view()。对于高维数组a，可以指定转置的轴的顺序。若不指定转置的轴的顺序，a.shape = (i[0], i[1], ... i[n-2], i[n-1]), then a.transpose().shape = (i[n-1], i[n-2], ... i[1], i[0]). <br>
&emsp;&emsp;a.T也表示 a 的转置，与a.tranpose()含义相同，但不能使用任何输入参数。

In [461]:
x = np.arange(12).reshape(3,4)
print('x =\n', x)
x1 = np.transpose(x)
x2 = x.transpose()
x3 = x.T
print('np.transpose(x) =\n', x1)
print('x.transpose() =\n', x2)
print('x.T =\n', x3)
x[1][2] = 100
print(x1)
print(x2)
print(x3)

x =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
np.transpose(x) =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
x.transpose() =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
x.T =
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[  0   4   8]
 [  1   5   9]
 [  2 100  10]
 [  3   7  11]]
[[  0   4   8]
 [  1   5   9]
 [  2 100  10]
 [  3   7  11]]
[[  0   4   8]
 [  1   5   9]
 [  2 100  10]
 [  3   7  11]]


In [465]:
# 对一维数组，transpose产生该数组的view()
y = np.arange(4)
y1 = np.transpose(y)
y2 = y.T
print('y =\n', y)
print('y1 =\n', y1)
print('y2 =\n', y2)
y.shape = 2,2
print('y =\n', y)
print('y1 =\n', y1)
print('y2 =\n', y2)
y[0][1] = 100
print('y =\n', y)
print('y1 =\n', y1)
print('y2 =\n', y2)

y =
 [0 1 2 3]
y1 =
 [0 1 2 3]
y2 =
 [0 1 2 3]
y =
 [[0 1]
 [2 3]]
y1 =
 [0 1 2 3]
y2 =
 [0 1 2 3]
y =
 [[  0 100]
 [  2   3]]
y1 =
 [  0 100   2   3]
y2 =
 [  0 100   2   3]


In [29]:
# 三维数组的transpose()
x = np.arange(24).reshape(3,4,2)
y = np.transpose(x)  # 相当于transpose(x, (2,1,0))，新数组的shape为(2, 4, 3)
z = x.transpose((2,0,1))  # 新数组的shape为(2, 3, 4)
print('x =\n', x)
print('y =\n', y)
print('z =\n', z)

x =
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
y =
 [[[ 0  8 16]
  [ 2 10 18]
  [ 4 12 20]
  [ 6 14 22]]

 [[ 1  9 17]
  [ 3 11 19]
  [ 5 13 21]
  [ 7 15 23]]]
z =
 [[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]]]


<font face='kaiti' size=5 style='line-height:1.5'>

2. 数组堆叠： 
hstack(), vstack(): 数组的横向、纵向堆叠；

In [213]:
m1 = np.array([[0, 1], [2, 3]])
print('m1 =\n', m1)
m2 = np.arange(3,7).reshape(2,2)
print('m2 =\n', m2)
print('np.hstack(m1, m2) =\n', np.hstack([m1, m2]))
print('np.vstack(m1, m2) =\n', np.vstack((m1, m2)))

m1 =
 [[0 1]
 [2 3]]
m2 =
 [[3 4]
 [5 6]]
np.hstack(m1, m2) =
 [[0 1 3 4]
 [2 3 5 6]]
np.vstack(m1, m2) =
 [[0 1]
 [2 3]
 [3 4]
 [5 6]]


## 数组与数值的运算<br>
<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;数组与数值之间的可以使用'+, -, *, /, //, %, **'等运算符进行运算，这些运算都是数组的每个元素和数值之间进行对应运算，返回一个新数组。数组与数值之间也可以进行关系运算，返回一个布尔数组。另外，数组与数值之间还可以进行位运算。

In [432]:
x = np.arange(8).reshape(2,4)
print('x =\n', x, '\n')
print('x * 2 =\n', x*2, '\n')
print('x + 2 =\n', x + 2, '\n')
print('x/2 =\n', x / 2, '\n')
print('2/x =\n', 2 / x, '\n')  # 此处产生被 0 除的异常
print('x//2 =\n', x//2, '\n')
print('x % 2 =\n', x % 2, '\n')
print('x ** 2 =\n', x ** 2, '\n')
print('x > 2 =\n', x > 2)   # 关系运算
print('x << 2 =\n', x << 2)  # 向左移位

x =
 [[0 1 2 3]
 [4 5 6 7]] 

x * 2 =
 [[ 0  2  4  6]
 [ 8 10 12 14]] 

x + 2 =
 [[2 3 4 5]
 [6 7 8 9]] 

x/2 =
 [[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]] 

2/x =
 [[       inf 2.         1.         0.66666667]
 [0.5        0.4        0.33333333 0.28571429]] 

x//2 =
 [[0 0 1 1]
 [2 2 3 3]] 

x % 2 =
 [[0 1 0 1]
 [0 1 0 1]] 

x ** 2 =
 [[ 0  1  4  9]
 [16 25 36 49]] 

x > 2 =
 [[False False False  True]
 [ True  True  True  True]]
x << 2 =
 [[ 0  4  8 12]
 [16 20 24 28]]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


## 数组与数组的运算<br>
<font face='kaiti' size=5 style='line-height:1.5'>
    
- 同样大小的数组之间的可以使用`+, -, *, /, //, %, **`等算术运算符进行运算，也可以进行关系运算以及位运算。这些运算都是数组的对应元素之间进行运算，返回一个新数组。<br>

In [313]:
a = np.random.randint(10, 50, (4,3), dtype='int64')  
b = np.arange(1,13).reshape(4,3)
print('a =\n', a)
print('b =\n', b)
print('a + b =\n', a + b)
print('a * b =\n', a * b)
print('a ** b =\n', a**b)
print('a > 2*b\n', a > 2*b)

a =
 [[14 32 45]
 [17 16 17]
 [14 30 44]
 [21 34 44]]
b =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a + b =
 [[15 34 48]
 [21 21 23]
 [21 38 53]
 [31 45 56]]
a * b =
 [[ 14  64 135]
 [ 68  80 102]
 [ 98 240 396]
 [210 374 528]]
a ** b =
 [[                  14                 1024                91125]
 [               83521              1048576             24137569]
 [           105413504         656100000000      618121839509504]
 [      16679880978201    70188843638032384 -2686141444351066112]]
a > 2*b
 [[ True  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]]


<font face='kaiti' size=5 style='line-height:1.5'>

- 数组之间也可以使用运算符`@`表示两个数组进行<font color=#ff0000>矩阵乘法</font>运算，要求两个数组的大小需符合矩阵乘法的规则。

In [435]:
a = np.array([[1,2,3],[2,3,4]])
b = np.arange(12).reshape(3,4)
print('a =\n', a)
print('b =\n', b)
print('a @ b =\n', a @ b)

a =
 [[1 2 3]
 [2 3 4]]
b =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a @ b =
 [[32 38 44 50]
 [44 53 62 71]]


<font face='kaiti' size=5 style='line-height:1.5'>

- 数组的运算也支持复合赋值运算符，如`+=, *=`等，这种赋值运算符将替换原数组的数据，而不产生新数组，但要求左边的数组大小与运算后的一致，不适用广播机制。

## 广播<br>
<font face='kaiti' size=5 style='line-height:1.5'>
    
&emsp;&emsp;Python的广播机制让行向量与矩阵、列向量与矩阵、行向量与列向量之间可以进行算术运算和关系运算。对行向量的规则是：将行向量复制成多行矩阵，行数与另一个的行数相同，两者间的运算变成两个矩阵的运算，能进行运算的前提是两者的列数相同。列向量的规则与之类似。

In [315]:
# 行向量与矩阵运算，相当于先将行向量a复制成同样大小的矩阵
a = np.array([1, 2, 3, 4])
b = np.arange(1,13).reshape(3, 4)
print('a =\n', a)
print('b =\n', b)
print('a + b =\n', a + b)
print('a * b =\n', a * b)
print('a ** b =\n', a**b)
print('2*a >= b\n', 2*a > b)

a =
 [1 2 3 4]
b =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a + b =
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]
a * b =
 [[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]]
a ** b =
 [[       1        4       27      256]
 [       1       64     2187    65536]
 [       1     1024   177147 16777216]]
2*a >= b
 [[ True  True  True  True]
 [False False False False]
 [False False False False]]


In [317]:
# 列向量与矩阵运算，相当于先将列向量a复制成一个同样大小的矩阵
a = np.arange(1,4).reshape(3,1)
b = np.arange(1,13).reshape(3, 4)
print('a =\n', a)
print('b =\n', b)
print('a + b =\n', a + b)
print('a * b =\n', a * b)
print('a ** b =\n', a**b)
print('3*a >= b\n', 3*a > b)

a =
 [[1]
 [2]
 [3]]
b =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a + b =
 [[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]
a * b =
 [[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]
a ** b =
 [[     1      1      1      1]
 [    32     64    128    256]
 [ 19683  59049 177147 531441]]
3*a >= b
 [[ True  True False False]
 [ True False False False]
 [False False False False]]


In [31]:
# 以下的运算相当于先将a，b均复制成一个3行4列的矩阵
a = np.arange(1,4).reshape(3,1)
b = np.arange(1,5)
print('a =\n', a)
print('b =\n', b)
print('a + b =\n', a + b)
print('a * b =\n', a * b)
print('a ** b =\n', a**b)
print('2*a > b\n', 2*a > b)

a =
 [[1]
 [2]
 [3]]
b =
 [1 2 3 4]
a + b =
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
a * b =
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]]
a ** b =
 [[ 1  1  1  1]
 [ 2  4  8 16]
 [ 3  9 27 81]]
2*a > b
 [[ True False False False]
 [ True  True  True False]
 [ True  True  True  True]]


## 线性代数<br>
<font face='kaiti' size=5 style='line-height:1.5'>

&emsp;&emsp;Numpy库提供了很多用于线性代数运算的函数， 如： dot(), vdot(), inner(), outer(), matmul(), trace()等函数，另外，还有专门用于线性代数运算的子模块linalg，其中常用的函数有det(), inv(), solve(), eig()等。

<font face='kaiti' size=5 style='line-height:1.5'>
    
1. `numpy.dot(a, b)`或`a.dot(b)`求数组a, b的点积。当a, b都是一维数组时，返回a, b的内积；当a, b都是二维数组时，返回a, b的矩阵乘积；当其中有一个是数时，返回数乘的结果。

In [331]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print(a.dot(b))
print(b.dot(a))

[2 3 4]
20
20


In [323]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(np.dot(a,b))

[[37 40]
 [85 92]]


In [332]:
# 注意： 这里a, b都是二维数组
a = np.array([[1, 2, 3]])
b = np.array([2, 3, 4]).reshape(3,1)
print(a.dot(b))
print(b.dot(a))

[[20]]
[[ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]]


<font face='kaiti' size=5 style='line-height:1.5'>
    
2. `numpy.vdot(a, b)`求向量a, b的点积。当a, b中存在多维数组时，先将其平铺为向量，再求内积。如果在复数域，则在求内积时需对第1个向量取共轭。

In [336]:
a = np.array([[1, 2, 3, 4]])
b = np.array([[11,12],[13,14]])
print(np.vdot(a, b))

130


<font face='kaiti' size=5 style='line-height:1.5'>
    
3. `numpy.inner(a, b)` 返回一维数组a, b的向量内积。对于更高的维度，它返回最后一个轴上的和的乘积。以下的例子相当于计算
```python
[1*11+2*12, 1*13+2*14 
 3*11+4*12, 3*13+4*14]
```

In [346]:
a = np.array([[1,2], [3,4]])  
print ('数组 a：')
print (a)

b = np.array([[11, 12], [13, 14]])  
print ('数组 b：')
print (b) 

print ('内积：')
print (np.inner(a,b))

数组 a：
[[1 2]
 [3 4]]
数组 b：
[[11 12]
 [13 14]]
内积：
[[35 41]
 [81 95]]


<font face='kaiti' size=5 style='line-height:1.5'>
    
4. `numpy.outer(a, b)` 返回一维数组a, b的向量外积。即`out[i, j] = a[i] * b[j]`，相当于矩阵乘法中列向量 a 乘上行向量 b。

In [343]:
a = np.array([1, 2, 3])
b = np.array([2, 4])
print(np.outer(a, b))

[[ 2  4]
 [ 4  8]
 [ 6 12]]


<font face='kaiti' size=5 style='line-height:1.5'>
    
5. `numpy.matmul(a, b)` 返回矩阵a, b的乘积。

In [344]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])
print(np.matmul(a, b))

[[ 8  5]
 [20 13]]


<font face='kaiti' size=5 style='line-height:1.5'>
    
6. `numpy.trace(a)`或`a.trace()` 返回矩阵a的迹，即矩阵对角线元素之和。

In [348]:
a = np.array([[1, 2], [3, 4]])
print(a.trace())
print(np.trace(a))

5
5


<font face='kaiti' size=5 style='line-height:1.5'>

7. Numpy的子模块linalg中，提供了`det(), inv(), eig(), solve()`等函数分别用于求矩阵的行列式，逆矩阵，特征值与特征向量，以及解方程组。

In [358]:
a = np.arange(1,5).reshape(2,2)
b = np.array([1, 2])
print('a =\n', a)
print('b =\n', b)
print('np.linalg.det(a) =\n', np.linalg.det(a))
print('np.linalg.inv(a) =\n', np.linalg.inv(a))
print('np.linalg.eig(a) =\n', np.linalg.eig(a))
print('求解ax = b, 得 x =\n', np.linalg.solve(a, b))

a =
 [[1 2]
 [3 4]]
b =
 [1 2]
np.linalg.det(a) =
 -2.0000000000000004
np.linalg.inv(a) =
 [[-2.   1. ]
 [ 1.5 -0.5]]
np.linalg.eig(a) =
 (array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
求解ax = b, 得 x =
 [0.  0.5]


<font face='kaiti' size=5 style='line-height:1.5'>
&emsp;&emsp;另外，linalg模块还提供了一些其他函数。cholesky()用于矩阵的cholesky分解；cond()用于求矩阵的条件数；lstsq()用于求方程组的最小二乘解；norm()用于求数组的范数；qr()用于矩阵的QR分解；svd()用于矩阵的奇异值分解。当需要时，自己查阅帮助。<br>
&emsp;&emsp;更多的，请查看 https://www.numpy.org/devdocs/reference/routines.linalg.html

## 数学函数

|函 数| 描 述 |
|:---|:---|
|abs(p), fabs(p)|数组p的各元素的绝对值|
|conj(p)|数组p的各元素的共轭|
|exp(p)|计算数组p的各元素的以e为底的指数函数值|
|log(p)|数组p的各元素的自然对数值|
|log2(p)|数组p的各元素的以2为底的对数值|
|log10(p)|数组p的各元素的以10为底的对数值|
|sqrt(p)|数组p的各元素的平方根|
|sin(p),cos(p),tan(p)|数组p的各元素的正弦值，余弦值，正切值|
|arcsin(p),arccos(p),arctan(p)|数组p的各元素的反正弦，反余弦，反正切|
|maximum(a, b),fmax(a,b)|数组a,b中逐元素求最大值|
|minimum(a, b),fmin(a,b)|数组a,b中逐元素求最小值|
|isfinite(a)|逐元素检测数组a元素是否有限值|
|isinf(a)|逐元素检测数组a中元素是否无穷大|
|isnan(a)|逐元素检测数组a中元素是否非数NaN|
|isnat(a)|逐元素检测数组a中元素是否非时间Not a time|
|round(a)|逐元素对数组a中元素做四舍五入|
|floor(a)|逐元素对数组a中元素向下取整|
|ceil(a)|逐元素对数组a中元素向上取整|
|fix(a)|逐元素对数组a中元素做截尾取整|
|sign(a)|逐元素求数组a中元素的符号|
|prod(a[, axis, ...])|数组a沿某轴求元素的乘积|
|sum(a[, axis, ...])|数组a沿某轴求元素的和|

更多请查看 https://www.numpy.org/devdocs/reference/routines.math.html

## 排序、搜索、计数

|函 数| 描 述 |
|:---|:---|
|sort(a[, axis, kind, order])|对数组a沿某轴排序|
|argsort(a[, axis, kind, order])|对数组a沿某轴排序，返回原索引号|
|a.sort([axis, kind, order])|对数组a沿某轴排序，排序后的数组替代原数组|
|argmax(a[, axis, out])|对数组a沿某轴求最大值，返回最大值元素索引号|
|argmin(a[, axis, out])|对数组a沿某轴求最小值，返回最小值元素索引号|
|nonzero(a)|返回数组a的非零元的索引号|
|where(condition, [x, y])|按条件condition，在x或y中选择元素返回|
|count_nonzero(a[, axis])|对数组a沿某轴的非零元计数|

更多请查看 https://www.numpy.org/devdocs/reference/routines.sort.html

In [12]:
import numpy as np
np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])]
np.r_[-1:1:6j, [0]*3, 5, 6]
np.array([ [1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

## 统计函数

| 函 数 | 描 述 |
|:---|:---|
|amin(a[,axis, ...])|对数组a沿某轴求最小值|
|amax(a[,axis, ...])|对数组a沿某轴求最大值|
|ptp(a[,axis, ...])|对数组a沿某轴求取值范围|
|percentile(a, q[, axis,...])|对数组a沿某轴求百分位数|
|quantile(a, q[, axis,...])|对数组a沿某轴求分位数|
|median(a[, axis, ...])|对数组a沿某轴求中位数|
|average(a[, axis, weights,...])|对数组a沿某轴求加权平均数|
|mean(a[, axis, ...])|对数组a沿某轴求平均值|
|std(a[, axis,...])|对数组a沿某轴求标准差|
|var(a[, axis, ...])|对数组a沿某轴求方差|
|corrcoef(x[, y,...])|返回Pearson相关系数|
|correlate(a, v[, mode])|返回2个一维向量的互相关系数|
|cov(m[, y,...])|估计协方差矩阵|
|histogram(a[, bins, range,...])| 计算数据集的直方图|

更多请查看 https://www.numpy.org/devdocs/reference/routines.statistics.html

In [6]:
import numpy as np
a=np.arange(24)
b=a.reshape(1,3,8)
print(b)

[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]]]


In [9]:
c=np.array([1,2,3,4,5,6])
print(c)
d=np.array(c)
print(d)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [10]:
np.sum(c)

21

In [11]:
len(c)

6

In [13]:
np.arange(5)[1]

1

In [14]:
np.ones(1)

array([1.])